CMakeLists.txt
configure.ac
m4/ax_cxx_compile_stdcxx.m4

* Autoconf supports building with C++17, C++14 or C++11 (using ax_cxx_compile_stdcxx.m4)
* CMake supports up to C++17 (previously C++14)

XERCESC-2141: Enable C++17, C++14 or C++11 when available

---

.travis.yml
scripts/ci-travis

* Use Ubuntu bionic image (was trusty)
* Install all build dependencies with apt (Linux) or homebrew (MacOS X)

XERCESC-2201: Upgrade travis-ci

---

scripts/ci-appveyor-setup

ICU have changed their download URLs to GitHub releases.  Update accordingly.
This is a minimal AppVeyor fix; the base image update will need a newer ICU.

XERCESC-2200: Appveyor bug fix

---

scripts/ci-appveyor-setup

ICU have changed their download URLs to GitHub releases. Update accordingly.
This is a minimal AppVeyor fix; the base image update will need a newer ICU.

XERCESC-2200: Appveyor bug fix (3.2)

---

src/xercesc/util/Transcoders/ICU/ICUTransService.cpp

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35373
When charsDecoded == 0, the line ``for (index = 0; index < charsDecoded- 1; index++)`` will cause to read out of bounds of fSrcOffsets, due to unsigned integer underflow rules.
Can be verified with the attached (broken) XML file: [test.gml.zip](https://github.com/apache/xerces-c/files/6960822/test.gml.zip)
This should be backported to the 3.2 branch

XERCESC-2217: ICUTranscoder::transcodeFrom(): fix read heap-buffer-overflow

---

src/xercesc/util/Transcoders/ICU/ICUTransService.cpp

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35373
When charsDecoded == 0, the line ``for (index = 0; index < charsDecoded - 1; index++)`` will cause to read out of bounds of fSrcOffsets, due to unsigned integer underflow rules.
Backport of https://github.com/apache/xerces-c/pull/24

XERCESC-2217: [Backport 3.2] ICUTranscoder::transcodeFrom(): fix read heap-buffer-overflow

---

src/xercesc/util/NetAccessors/Curl/CurlURLInputStream.cpp
src/xercesc/util/NetAccessors/Curl/CurlURLInputStream.hpp

CurlURLInputStream constructor calls the readMore() method, which can
throw exceptions. In that situation, the destructor is not called, which
results in resource/memory leaks. To fix that, catch the exceptions,
manually do the cleanup and rethrow the exceptions.
Found by ossfuzz (locally)

XERCESC-2218: CurlURLInputStream constructor: avoid memory leak

---

src/xercesc/util/NetAccessors/Curl/CurlURLInputStream.cpp
src/xercesc/util/NetAccessors/Curl/CurlURLInputStream.hpp

CurlURLInputStream constructor calls the readMore() method, which can
throw exceptions. In that situation, the destructor is not called, which
results in resource/memory leaks. To fix that, catch the exceptions,
manually do the cleanup and rethrow the exceptions.
Found by ossfuzz (locally)
Backport of https://github.com/apache/xerces-c/pull/28

XERCESC-2218: [Backport 3.2] CurlURLInputStream constructor: avoid memory leak

---

src/xercesc/internal/ReaderMgr.cpp
src/xercesc/internal/XMLReader.cpp
src/xercesc/internal/XMLReader.hpp

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37529 on GDAL
The backtrace of the exception that caused the memory leak was:
```
Catchpoint 1 (exception thrown), 0x00007ffff5547672 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
0  0x00007ffff5547672 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
1  0x00007ffff24447c4 in xercesc_4_0::PosixFileMgr::fileRead (this=<optimized out>, f=<optimized out>, byteCount=<optimized out>, buffer=<optimized out>, manager=0x5555556df730)
at xercesc/util/FileManagers/PosixFileMgr.cpp:160
2  0x00007ffff24e6ec2 in xercesc_4_0::XMLReader::refreshRawBuffer (this=0x5555557e49f8) at xercesc/internal/XMLReader.cpp:1891
3  0x00007ffff24e70d4 in xercesc_4_0::XMLReader::XMLReader (this=0x5555557e49f8, pubId=<optimized …
```

XERCESC-2219: XMLReader constructor: fix memory leak when refreshRawBuffer() throws

---

src/xercesc/internal/ReaderMgr.cpp
src/xercesc/internal/XMLReader.cpp
src/xercesc/internal/XMLReader.hpp

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37529 on GDAL
The backtrace of the exception that caused the memory leak was:
```
Catchpoint 1 (exception thrown), 0x00007ffff5547672 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
0  0x00007ffff5547672 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
1  0x00007ffff24447c4 in xercesc_4_0::PosixFileMgr::fileRead (this=<optimized out>, f=<optimized out>, byteCount=<optimized out>, buffer=<optimized out>, manager=0x5555556df730)
at xercesc/util/FileManagers/PosixFileMgr.cpp:160
2  0x00007ffff24e6ec2 in xercesc_4_0::XMLReader::refreshRawBuffer (this=0x5555557e49f8) at xercesc/internal/XMLReader.cpp:1891
3  0x00007ffff24e70d4 in xercesc_4_0::XMLReader::XMLReader (this=0x5555557e49f8, pubId=<optimized …
```

XERCESC-2219: [Backport 3.2] XMLReader constructor: fix memory leak when refreshRawBuffer() throws

---

src/xercesc/util/MsgLoaders/InMemory/InMemMsgLoader.cpp

Seen with the IconvGNU transcoder when parsing "<aaa.xsdopengis.net/gml\x96".
The reason is that XMLString::transcode(repText2, manager) throws a TranscodingException
which causes the tmp1 string to leak.
```
0 0x8791409 in operator new(unsigned int) /src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:99:3
1 0xbd147f7 in xercesc_4_0::MemoryManagerImpl::allocate(unsigned int) gdal/xerces-c/src/xercesc/internal/MemoryManagerImpl.cpp:40:18
2 0xbe8c73e in xercesc_4_0::IconvGNULCPTranscoder::transcode(char const*, xercesc_4_0::MemoryManager*) gdal/xerces-c/src/xercesc/util/Transcoders/IconvGNU/IconvGNUTransService.cpp:870:32
3 0xbc22ca2 in xercesc_4_0::XMLString::transcode(char const*, xercesc_4_0::MemoryManager*) gdal/xerces-c/src/xercesc/util/XMLString.cpp:621:25
4 0xbe8f4ad in …
```

XERCESC-2221: InMemMsgLoader::loadMsg(): fix memory leak when transcoding fails.

---

src/xercesc/util/XMLChTranscoder.cpp
src/xercesc/util/XMLUTF16Transcoder.cpp

Fixes:
xercesc/util/XMLChTranscoder.cpp:73:23: warning: setting buffer to a 'sizeof' expression; did you mean to transpose the last two arguments? [-Wmemset-transposed-args]
memset(charSizes, sizeof(XMLCh), countToDo);
^
xercesc/util/XMLChTranscoder.cpp:73:23: note: cast the second argument to 'int' to silence
and
xercesc/util/XMLUTF16Transcoder.cpp:114:23: warning: setting buffer to a 'sizeof' expression; did you mean to transpose the last two arguments? [-Wmemset-transposed-args]
memset(charSizes, sizeof(UTF16Ch), countToDo);
^
xercesc/util/XMLUTF16Transcoder.cpp:114:23: note: cast the second argument to 'int' to silence
1 warning generated.

Fix -Wmemset-transposed-args warnings of clang++

---

src/xercesc/validators/common/DFAContentModel.cpp

If a memory allocation of conflictTable[] fails, or later in the
function, the array is not freed.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38533

[XERCESC-2222] DFAContentModel::checkUniqueParticleAttribution(): fix memory leak

---

src/xercesc/validators/common/DFAContentModel.cpp

The complexity of this method is roughly O(n^3). Fuzzers can generate
schemas with n = several thousands. The test fTransTable[i][j] == XMLContentModel::gInvalidTrans
is independant of the k loop, and can thus being moved at a upper level
to improve runtime.

[XERCESC-2224] DFAContentModel::checkUniqueParticleAttribution (): speed enhancement

---

CMakeLists.txt

* Required for CURL imported target usage in XERCESC-2225
* Drop old cmake_policy settings which are now the default behaviour

XERCESC-2226: Update minimum CMake version to 3.12

---

src/xercesc/util/XercesDefs.hpp

* Restore previous behaviour (XMLSize_t is size_t)
* Remove XMLSSize_t (no uses in the codebase)

XERCESC-2208: XMLSize_t size_t revert

---

src/xercesc/internal/IGXMLScanner.cpp

The method can leak pubId and sysId when subsequent call to
fReaderMgr.skipPastSpaces() throws an exception (e.g. a
TranscodingException)

[XERCESC-2229] IGXMLScanner::scanDocTypeDecl(): fix memory leak on exception

---

src/xercesc/validators/common/DFAContentModel.cpp

Fixes GDAL's https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40866

[XERCESC-2230] DFAContentModel::buildSyntaxTree(): fix memory leaks when OutOfMemoryException occurs

---

src/xercesc/validators/common/DFAContentModel.cpp

Due to a copy&paste issue, the intended zero-initialization of
fFollowList wasn't done (copy&paste issue), and thus in case of
OutOfMemory exception when initializing the array, the memory freeing in
cleanup() could access uninitialized elements.
Follow-up of https://github.com/apache/xerces-c/pull/40 / a65990d79d3fc333d7481f010da4e165a88b6cb3
Fixes GDAL's https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42636

[XERCESC-2235] DFAContentModel::buildDFA(): correctly zero-initialize fFollowList

---

src/CMakeLists.txt
tests/CMakeLists.txt

Fixes https://issues.apache.org/jira/browse/XERCESC-2236, where trying to use the generated CMake config package doesn't work because the dependencies are not loaded using `find_package` in the config package. This change assumes they're not necessary for users of the library and marks them as `PRIVATE` so they don't end up in the config package in the first place.

Mark Dependencies as `PRIVATE` in CMake

---

tests/src/ThreadTest/ThreadTest.cpp

Contributed by STMicroelectronics

The windows.h header files is with lower case
